//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBingo.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bingo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bingo()
        {
            this.BingoPremio = new HashSet<BingoPremio>();
            this.Cartela = new HashSet<Cartela>();
        }
    
        public int IdBingo { get; set; }
        [Required]
        public Nullable<System.DateTime> DataHora { get; set; }
        [Required]
        public string Descricao { get; set; }
        public string Status { get; set; }
        public string DscCancelamenrto { get; set; }
        public Nullable<System.DateTime> DataCancelamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BingoPremio> BingoPremio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cartela> Cartela { get; set; }
    }
}
