//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBingo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BingoPremio
    {
        public int IdBingo { get; set; }
        public int IdPremio { get; set; }
        public int Id { get; set; }
    
        public virtual Bingo Bingo { get; set; }
        public virtual Premio Premio { get; set; }
    }
}
