//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBingo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartela
    {
        public int IdCartela { get; set; }
        public string DescricaoNumeros { get; set; }
        public Nullable<int> NumerosAcertos { get; set; }
        public Nullable<int> IdBingo { get; set; }
        public Nullable<int> N1 { get; set; }
        public Nullable<int> N2 { get; set; }
        public Nullable<int> N3 { get; set; }
        public Nullable<int> N4 { get; set; }
        public Nullable<int> N5 { get; set; }
        public Nullable<int> N6 { get; set; }
        public Nullable<int> N7 { get; set; }
        public Nullable<int> N8 { get; set; }
        public Nullable<int> N9 { get; set; }
        public Nullable<int> N10 { get; set; }
        public Nullable<int> N11 { get; set; }
        public Nullable<int> N12 { get; set; }
        public Nullable<int> N13 { get; set; }
        public Nullable<int> N14 { get; set; }
        public Nullable<int> N15 { get; set; }
    
        public virtual Bingo Bingo { get; set; }
    }
}
