//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBingo.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bingo> Bingo { get; set; }
        public virtual DbSet<BingoPremio> BingoPremio { get; set; }
        public virtual DbSet<Cartela> Cartela { get; set; }
        public virtual DbSet<Premio> Premio { get; set; }
    
        [DbFunction("Database1Entities", "FNGerarCartela")]
        public virtual IQueryable<FNGerarCartela_Result> FNGerarCartela()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FNGerarCartela_Result>("[Database1Entities].[FNGerarCartela]()");
        }
    
        public virtual int PRC_GerarCartelas(Nullable<int> bingoId)
        {
            var bingoIdParameter = bingoId.HasValue ?
                new ObjectParameter("BingoId", bingoId) :
                new ObjectParameter("BingoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRC_GerarCartelas", bingoIdParameter);
        }
    }
}
